Repository Team-Smeme/Smeme-iOS, pull requests merged in 2023-01, with the labels that each got.

#2 [Setting] #1 - 프로젝트 초기세팅
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/AccentColor.colorset/Contents.json
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/AppIcon.appiconset/Contents.json
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/Contents.json
  Smeme-iOS/Smeme-iOS/Resources/Constant/Constant.swift
  Smeme-iOS/Smeme-iOS/Resources/DesignSystem/DesignSystem.swift
  Smeme-iOS/Smeme-iOS/Resources/Extension/UIColor+.swift
  Smeme-iOS/Smeme-iOS/Resources/Extension/UIFont+.swift
  Smeme-iOS/Smeme-iOS/Resources/Extension/UIView+.swift
  Smeme-iOS/Smeme-iOS/Resources/Extension/UIViewController+.swift
  Smeme-iOS/Smeme-iOS/Resources/Font/Font.swift
  Smeme-iOS/Smeme-iOS/Resources/Storyboard/Base.lproj/LaunchScreen.storyboard
  Smeme-iOS/Smeme-iOS/Resources/Support/AppDelegate.swift
  Smeme-iOS/Smeme-iOS/Resources/Support/Info.plist
  Smeme-iOS/Smeme-iOS/Resources/Support/SceneDelegate.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/API/API.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Base/BaseTargetType.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Base/GeneralResponse.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Base/MoyaLoggingPlugin.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Base/NetworkConstant.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Base/URLConstant.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/DataModel.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Service/Service.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/ViewController.swift
Labels: 짠 ✨, setting

#4 [Setting] #3 - SwiftLint 적용
  .gitignore
  Smeme-iOS/.swiftlint.yml
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Smeme-iOS/Smeme-iOS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Smeme-iOS/Smeme-iOS/Resources/Extension/UIViewController+.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Base/GeneralResponse.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Base/MoyaLoggingPlugin.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/ViewController.swift
Labels: 짠 ✨, setting

#11 [Setting] #1 - 프로젝트 추가 세팅
  .github/PULL_REQUEST_TEMPLATE.md
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Resources/Extension/UIViewController+.swift
  Smeme-iOS/Smeme-iOS/Resources/Protocol/ViewModel.swift
  Smeme-iOS/Smeme-iOS/Resources/Support/SceneDelegate.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/OpenDiary/OpenDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/ScrapStash/ScrapStashViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/TabBar/TabBarController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/ViewController.swift
Labels: 짠 ✨, setting

#14 [Feat] 스크랩 보관함 뷰 상단부 UI 구현
  Smeme-iOS/Smeme-iOS/Sources/Screen/ScrapStash/ScrapStashViewController.swift
Labels: 쫑 ✨, Feat

#16 [Feat] #1 - UILabel Line Height 메서드 추가
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Resources/Extension/UILabel+.swift
Labels: 짠 ✨, setting

#15 [Feat] NaviView UI 구현
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryForiegn/DiaryForiegnViewController.swift
Labels: 쭌 ✨, Feat

#22 [Feat] #18 - 키보드 notification 구현
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Resources/Extension/UIScreen+.swift
  Smeme-iOS/Smeme-iOS/Resources/Extension/UIViewController+.swift
  Smeme-iOS/Smeme-iOS/Resources/Support/AppDelegate.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryForiegn/DiaryForeignViewController.swift
Labels: 짠 ✨, Feat

#24 [Feat] #23 - 로그인 UI 구현
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/btnkakaoLogin.imageset/Contents.json
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/btnkakaoLogin.imageset/btnkakaoLogin.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/btnkakaoLogin.imageset/btnkakaoLogin@2x.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/btnkakaoLogin.imageset/btnkakaoLogin@3x.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/logoSmeme.imageset/Contents.json
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/logoSmeme.imageset/smemeLogo.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/logoSmeme.imageset/smemeLogo@2x.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/logoSmeme.imageset/smemeLogo@3x.png
  Smeme-iOS/Smeme-iOS/Resources/Constant/Image.swift
  Smeme-iOS/Smeme-iOS/Resources/Extension/UIViewController+.swift
  Smeme-iOS/Smeme-iOS/Resources/Support/AppDelegate.swift
  Smeme-iOS/Smeme-iOS/Resources/Support/Info.plist
  Smeme-iOS/Smeme-iOS/Resources/Support/SceneDelegate.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/Login/LoginViewController.swift
Labels: 짠 ✨, Feat

#26 [Feat] #25 - TextView Line Height 구현
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Resources/Extension/UITextView+.swift
Labels: 짠 ✨, Feat

#28 [Feat] #13 - 랜덤주제뷰 DesignSystem에 추가
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Resources/DesignSystem/RandomSubjectView.swift
  Smeme-iOS/Smeme-iOS/Resources/Extension/UIColor+.swift
  Smeme-iOS/Smeme-iOS/Resources/Extension/UILabel+.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryViewController.swift
Labels: 쭈 🏋️‍♀️

#30 [Feat] #9 - MyDiary뷰 상단 네비게이션바 UI 구현
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Resources/DesignSystem/RandomSubjectView.swift
  Smeme-iOS/Smeme-iOS/Resources/Extension/UIView+.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryNavigationBar.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryViewController.swift
Labels: 쭈 🏋️‍♀️, Feat

#29 [Feat] #19 DiaryForeign BottomView UI 구현
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Resources/Extension/UIView+.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryForeign/DiaryForeignViewController.swift
Labels: 쭌 👳‍♂️, Feat

#33 [Feat] #27 - 오픈 일기 headerView UI 구현
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Resources/Extension/UIView+.swift
  Smeme-iOS/Smeme-iOS/Resources/Support/SceneDelegate.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/Login/LoginViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/OpenDiary/OpenDiaryCollectionViewCell.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/OpenDiary/OpenDiaryViewController.swift
Labels: 짠 ✨, Feat

#37 [Chore] #36 - 오류 코드 수정
  Smeme-iOS/Smeme-iOS/Resources/Extension/UIView+.swift
Labels: 짠 ✨, Chore

#40 [Feat] #35 TextView UI, 기능 구현
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryForeign/DiaryForeignViewController.swift
Labels: 쭌 👳‍♂️, Feat

#42 [Feat] #32 - MyDiaryView 플로팅버튼 구현
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Resources/Constant/Image.swift
  Smeme-iOS/Smeme-iOS/Resources/Extension/UIView+.swift
  Smeme-iOS/Smeme-iOS/Resources/Extension/UIViewController+.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/IconWithTextButton.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryDateBar.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryFloatingButtonViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryNavigationBar.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryViewController.swift
Labels: 쭈 🏋️‍♀️, Feat

#48 [Chore] #45 - native app key 수정
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Resources/Support/AppDelegate.swift
  Smeme-iOS/Smeme-iOS/Resources/Support/Info.plist
  Smeme-iOS/Smeme-iOS/Sources/Network/Base/Environment.swift
Labels: 짠 ✨, Chore

#50 [Chore] #49 - 카카오버튼 에셋 이름 카멜케이스로 변경
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/btnkakaoLogin.imageset/Contents.json
Labels: 쭈 🏋️‍♀️, Chore

#51 [Feat] #39 - 토스트 메세지 구현
  Smeme-iOS/Smeme-iOS/Resources/Extension/UIViewController+.swift
Labels: 쫑 🎀, Feat

#52 [Feat] #38 - 오픈 일기 리스트 컬렉션뷰 UI 구현
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/btnTranslate.imageset/Contents.json
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/btnTranslate.imageset/btnTranslateOff.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/btnTranslate.imageset/btnTranslateOff@2x.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/btnTranslate.imageset/btnTranslateOff@3x.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/btnTranslateSelected.imageset/Contents.json
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/btnTranslateSelected.imageset/btnTranslateOn.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/btnTranslateSelected.imageset/btnTranslateOn@2x.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/btnTranslateSelected.imageset/btnTranslateOn@3x.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/icnLikeSelected.imageset/Contents.json
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/icnLikeSelected.imageset/btnLikeSelected.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/icnLikeSelected.imageset/btnLikeSelected@2x.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/icnLikeSelected.imageset/btnLikeSelected@3x.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/icnLikeSmall.imageset/icnThumbsUpSmall.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/icnLikeSmall.imageset/icnThumbsUpSmall@2x.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/icnLikeSmall.imageset/icnThumbsUpSmall@3x.png
  Smeme-iOS/Smeme-iOS/Resources/Constant/Image.swift
  Smeme-iOS/Smeme-iOS/Resources/Extension/UITextView+.swift
  Smeme-iOS/Smeme-iOS/Resources/Extension/UIView+.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/OpenDiary/DiaryListCollectionViewCell.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/OpenDiary/OpenDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/OpenDiary/TopicCollectionViewCell.swift
Labels: 짠 ✨, Feat

#55 [Feat] #41 - RandomSubjectButton 기능 구현
  Smeme-iOS/Smeme-iOS/Resources/Extension/UIViewController+.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryForeign/DiaryForeignViewController.swift
Labels: 쭌 👳‍♂️, Feat

#56 [Feat] #53 오픈 일기 상세 headerView UI 구현
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Sources/Network/Base/Environment.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/DetailOpenDiary/DetailOpenDiaryViewController.swift
Labels: 짠 ✨, Feat

#54 [Feat] #17 스크랩 보관함 뷰 컬렉션 뷰 UI 구현
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/ScrapedExpressionModel.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/ScrapStash/ScrapStashViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/ScrapStash/ScrapedListCollectionViewCell.swift
Labels: 쫑 🎀, Feat

#60 [Feat] #57 - 오픈 일기 상세뷰 bottom View UI
  Smeme-iOS/Smeme-iOS/Sources/Screen/DetailOpenDiary/DetailOpenDiaryViewController.swift
Labels: 짠 ✨, Feat

#59 [Feat] #43 - MyDiary뷰 콜렉션뷰 구현
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Resources/Extension/UILabel+.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryCollectionViewCell.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryViewController.swift
Labels: 쭈 🏋️‍♀️, Feat

#61 [Feat] #34 - 마이 스밈 뷰 상단부~❤️ UI 구현
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Sources/Screen/MySmeme/MySmemeViewController.swift
Labels: 쫑 🎀, Feat

#64 [Feat] #45 - 내일기상세뷰 UI 구현
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Resources/Extension/String+.swift
  Smeme-iOS/Smeme-iOS/Resources/Extension/UIViewController+.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/MyDiaryDetail.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/DetailMyDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryCollectionViewCell.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryDateBar.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryFloatingButtonViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryNavigationBar.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryViewController.swift
Labels: 쭈 🏋️‍♀️, Feat

#70 [Feat] #68 DiaryKorean NaviView
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryKorean/DiaryKoreanStepOneViewController.swift
Labels: 쭌 👳‍♂️, Feat

#72 [Chore] #71 - SwiftLine 수정
  Smeme-iOS/.swiftlint.yml
Labels: 짠 ✨, Chore

#74 [Feat] #65 - 좋아요 나타내는 바텀뷰 추가
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Resources/Extension/UIView+.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/DetailMyDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/Subviews/IconWithTextButton.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/Subviews/LikeBottomView.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/Subviews/MyDiaryDateBar.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/Subviews/MyDiaryNavigationBar.swift
Labels: 쭈 🏋️‍♀️, Feat

#73 [Feat] #63 - 마이스밈 뷰 UI 구현
  Smeme-iOS/Smeme-iOS/Sources/Screen/MySmeme/MySmemeViewController.swift
Labels: 쫑 🎀, Feat

#88 [Chore] #82 - APIConstant 파일 생성
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Sources/Network/Base/APIConstant.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Base/Environment.swift
Labels: 짠 ✨, Chore

#90 [Chore] #82 - .gitignore 수정
  .gitignore
Labels: 짠 ✨, Chore

#92 [Feat] #82 - gitignore에 APIConstant파일 추가
  .gitignore
  Smeme-iOS/Smeme-iOS/Sources/Network/Base/APIConstant.swift
Labels: 쭈 🏋️‍♀️, Feat

#93 [Chore] #82 - APIConstant
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
Labels: 짠 ✨, Chore

#80 [Feat] #76 - 스플래시 뷰 구현
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Sources/Screen/Splash/SplashViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/Splash/smemeSplash.json
Labels: 쫑 🎀, Feat

#94 [Chore] #89 - 에셋 추가, 상수화
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/icnPageRightSmall.imageset/Contents.json
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/icnPageRightSmall.imageset/icnMypageDetail.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/icnPageRightSmall.imageset/icnMypageDetail@2x.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/icnPageRightSmall.imageset/icnMypageDetail@3x.png
  Smeme-iOS/Smeme-iOS/Resources/Constant/Image.swift
  Smeme-iOS/Smeme-iOS/Resources/Support/AppDelegate.swift
Labels: 쫑 🎀, Chore

#87 [Feat] #77 - Step2 TextView UI 구현
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryKorean/StepOneKoreanDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryKorean/StepTwoKoreanDiaryViewController.swift
Labels: 쭌 👳‍♂️, Feat

#95 [Feat] #83 - Step1 BottomView UI 구현
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryKorean/StepOneKoreanDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryKorean/StepTwoKoreanDiaryViewController.swift
Labels: 쭌 👳‍♂️, Feat

#97 [Feat] #25 - textView Line Spacing 메서드 구현
  Smeme-iOS/Smeme-iOS/Resources/Extension/UITextView+.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryKorean/StepOneKoreanDiaryViewController.swift
Labels: 짠 ✨, Feat

#98 [Feat] #96 - Step2 BottomView UI 구현
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryKorean/StepTwoKoreanDiaryViewController.swift
Labels: 쭌 👳‍♂️, Feat

#99 [Chore] #25 - textView lineHeight 주석 추가
  Smeme-iOS/Smeme-iOS/Resources/Extension/UITextView+.swift
Labels: 짠 ✨, Chore

#103 [Feat] #100 - StepOneKoreanDiaryViewController 랜덤 주제 버튼 기능 구현
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryKorean/StepOneKoreanDiaryViewController.swift
Labels: 쭌 👳‍♂️, Feat

#104 [Feat] #67 - 회원가입뷰 UI 구현 및 키보드에 따른 액션 처리
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/btnWelcome.imageset/Contents.json
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/btnWelcome.imageset/btnWelcome.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/btnWelcome.imageset/btnWelcome@2x.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/btnWelcome.imageset/btnWelcome@3x.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/btnWelcomeInactive.imageset/Contents.json
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/btnWelcomeInactive.imageset/btnWelcomeInactive.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/btnWelcomeInactive.imageset/btnWelcomeInactive@2x.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/btnWelcomeInactive.imageset/btnWelcomeInactive@3x.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/icnCircleX.imageset/Contents.json
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/icnCircleX.imageset/icnCircleX.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/icnCircleX.imageset/icnCircleX@2x.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/icnCircleX.imageset/icnCircleX@3x.png
  Smeme-iOS/Smeme-iOS/Resources/Constant/Image.swift
  Smeme-iOS/Smeme-iOS/Resources/Extension/UIViewController+.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/Login/ClearButtonTextField.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/Login/LoginProfileInfoViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/DetailMyDiaryViewController.swift
Labels: 쭈 🏋️‍♀️, Feat

#111 [Feat] #107 - open diary category API 연결
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Sources/Network/API/OpenDiaryCategoryAPI.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Base/BaseTargetType.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Base/NetworkConstant.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Base/URLConstant.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/OpenDiaryCategoryResponse.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Service/OpenDiaryCategoryService.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Service/Service.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/OpenDiary/OpenDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/OpenDiary/TopicCollectionViewCell.swift
Labels: 짠 ✨, Feat

#112 [Feat] #102 - 삭제 확인 alertController 구현
  Smeme-iOS/Smeme-iOS/Sources/Screen/ScrapStash/ScrapStashViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/ScrapStash/ScrapedListCollectionViewCell.swift
Labels: 쫑 🎀, Feat

#116 [Feat] #62 오픈 일기 상세뷰 scrollView 동적 구현
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/DetailOpenDiaryResponse.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/DetailOpenDiary/DetailOpenDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/OpenDiaryViewController.swift
Labels: 짠 ✨, Feat

#119 [Chore] #62 - textView 스크롤 막기
  Smeme-iOS/Smeme-iOS/Sources/Screen/DetailOpenDiary/DetailOpenDiaryViewController.swift
Labels: 짠 ✨, Chore

#117 [Feat] #110 - 내일기리스트 조회 API 연결
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Sources/Network/API/MyDiaryAPI.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Base/URLConstant.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/MyDiaryDetailResponse.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/MyDiaryListResponse.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Service/MyDiaryService.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryViewController.swift
Labels: 쭈 🏋️‍♀️, Feat

#123 [Feat] #105 - 옵션버튼 누를 시 action sheet, alert 구현
  Smeme-iOS/Smeme-iOS/Resources/Extension/UIView+.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/DetailMyDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/Subviews/MyDiaryDateBar.swift
Labels: 쭈 🏋️‍♀️, Feat

#124 [Feat] #113 - 스크랩보관함 뷰 토스트메세지 연결
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Resources/Extension/UIViewController+.swift
  Smeme-iOS/Smeme-iOS/Resources/Support/Info.plist
  Smeme-iOS/Smeme-iOS/Sources/Screen/ScrapStash/ScrapStashViewController.swift
Labels: 쫑 🎀, Feat

#126 [Feat] #118 - 오픈 일기 리스트 전체 조회 API 연결
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Sources/Network/API/API.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/API/OpenDiary/OpenDiary/DetailOpenDiaryResponse.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/API/OpenDiary/OpenDiary/OpenDiaryCategoryResponse.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/API/OpenDiary/OpenDiary/OpenDiaryListResponse.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/API/OpenDiary/OpenDiaryCategoryAPI.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/API/OpenDiary/OpenDiaryListAPI.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Base/URLConstant.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/DataModel.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/OpenDiary/DetailOpenDiaryResponse.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/OpenDiary/OpenDiaryCategoryResponse.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/OpenDiary/OpenDiaryListResponse.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Service/OpenDiary/OpenDiaryCategoryService.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Service/OpenDiary/OpenDiaryListService.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/OpenDiary/DiaryListCollectionViewCell.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/OpenDiary/OpenDiaryViewController.swift
Labels: 짠 ✨, Feat

#127 [Feat] #122 - 일기작성 뷰 2ea 서버통신 Network 세팅
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Sources/Network/API/PostDiary/PostDiaryAPI.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/API/RandomSubject/RandomSubjectAPI.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Base/URLConstant.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/RandomSubject/RandomSubjectResponse.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Service/PostDiary/PostDiaryService.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Service/RandomSubject/RandomSubjectService.swift
Labels: 쭌 👳‍♂️, Feat

#133 [Conflict] #131 - 충돌 해결
  Smeme-iOS/Smeme-iOS/Sources/Network/API/OpenDiary/OpenDiaryListAPI.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Service/OpenDiary/OpenDiaryListService.swift
Labels: Fix

#134 [Feat] #130 - URL constant 상수화
  Smeme-iOS/Smeme-iOS/Sources/Network/Base/URLConstant.swift
Labels: 쫑 🎀, Feat

#135 [Fix] #131 - URLConstant 수정
  Smeme-iOS/Smeme-iOS/Sources/Network/Base/URLConstant.swift
Labels: 짠 ✨, Fix

#141 [Feat] #136 - 마이 스밈 뷰 api 연결
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Sources/Network/API/MySmemeAPI.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/MySmemeResponse.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/ScrapStash/ScrapedExpressionResponse.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Service/MySmemeService.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MySmeme/MySmemeViewController.swift
Labels: 쫑 🎀, Feat

#143 [Feat] #137 - 오픈 일기 게시판 주제 카테고리 리스트 API 연결
  Smeme-iOS/Smeme-iOS/Sources/Network/API/OpenDiary/OpenDiaryListAPI.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Base/URLConstant.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Service/OpenDiary/OpenDiaryListService.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/OpenDiary/OpenDiaryViewController.swift
Labels: 짠 ✨, Feat

#138 [Feat] #120 - 내일기상세조회 API 연결
  Smeme-iOS/Smeme-iOS/Sources/Network/API/MyDiaryAPI.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/MyDiaryDetailResponse.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/MyDiaryListResponse.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Service/MyDiaryService.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/DetailMyDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryViewController.swift
Labels: 쭈 🏋️‍♀️, Feat

#145 [Feat] #66 - 내일기뷰 랜덤주제뷰 적용
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/DetailMyDiaryViewController.swift
Labels: 쭈 🏋️‍♀️, Feat

#146 [Feat] #132 - ForeignDiaryView RandomSubject API 연결
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryForeign/DiaryForeignViewController.swift
Labels: 쭌 👳‍♂️, Feat

#148 [Feat] #147 - StepOneKoreanDiaryView 랜덤주제버튼 API 서버통신
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryKorean/StepOneKoreanDiaryViewController.swift
Labels: 쭌 👳‍♂️, Feat

#152 [Feat] #142 - ScrapStash 뷰 delete api 연결
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Sources/Network/API/ScrapStash/ScrapStashAPI.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/ScrapedStashResponse.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Service/ScrapStash/ScrapStashService.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/ScrapStash/ScrapStashViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/ScrapStash/ScrapedListCollectionViewCell.swift
Labels: 쫑 🎀, Feat

#153 [Feat] #150 - 영어 일기 작성하기
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryForeign/DiaryForeignViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryFloatingButtonViewController.swift
Labels: 짠 ✨, Feat

#149 [Feat] #140 - 회원가입 API 연결
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Resources/Extension/UIViewController+.swift
  Smeme-iOS/Smeme-iOS/Resources/Support/SceneDelegate.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/API/SignUpAPI.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Service/SignUpService.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/Login/LoginProfileInfoViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryViewController.swift
Labels: 쭈 🏋️‍♀️, Feat

#156 [Chore] #140 - 함수 호출 코드 수정
  Smeme-iOS/Smeme-iOS/Sources/Screen/Login/LoginProfileInfoViewController.swift
Labels: Fix

#158 [Feat] #155 - 한국어 일기 작성하기 화면 전환 연결
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryForeign/DiaryForeignViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryKorean/StepOneKoreanDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryKorean/StepTwoKoreanDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryFloatingButtonViewController.swift
Labels: 짠 ✨, Feat

#159 [Feat] #157 - 탭바 커스텀
  Smeme-iOS/Smeme-iOS/Sources/Screen/TabBar/TabBarController.swift
Labels: 쫑 🎀, Feat

#162 [Feat] #161 - 일기 작성하기 API 구현
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Sources/Network/API/PostDiary/PostDiaryAPI.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/PostDiary/PostDiaryRequest.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/PostDiary/PostDiaryResponse.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Service/PostDiary/PostDiaryService.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryForeign/DiaryForeignViewController.swift
Labels: 짠 ✨, Feat

#160 [Feat] #144 - 오픈 일기 상세 페이지 API, 스크랩 API 연결
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Sources/Network/API/OpenDiary/DetailOpenDiaryAP.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/API/ScrapOpen/ScrapOpenDiaryAPI.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Base/URLConstant.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/SracpOpen/ScrapOpenDiaryResponse.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/SracpOpen/ScrapRequest.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Service/OpenDiary/DetailOpenDiaryService.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Service/ScrapOpen/ScrapOpenDirayService.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/DetailOpenDiary/DetailOpenDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/OpenDiary/DiaryListCollectionViewCell.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/OpenDiary/OpenDiaryViewController.swift
Labels: 짠 ✨, Feat

#165 [Feat] #139 - 내일기 delete API 연결
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Sources/Network/API/MyDiaryAPI.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Base/URLConstant.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Service/MyDiaryService.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/Login/LoginProfileInfoViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/DetailMyDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/ScrapStash/ScrapStashViewController.swift
Labels: 쭈 🏋️‍♀️, Feat

#167 [Fix] #166 - 내일기뷰 design issue 수정
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/icnPageLeftInactive.imageset/Contents.json
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/icnPageLeftInactive.imageset/icnPageLeftInactive.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/icnPageLeftInactive.imageset/icnPageLeftInactive@2x.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/icnPageLeftInactive.imageset/icnPageLeftInactive@3x.png
  Smeme-iOS/Smeme-iOS/Resources/Constant/Image.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/DetailMyDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/Subviews/MyDiaryDateBar.swift
Labels: 쭈 🏋️‍♀️, Fix

#169 [Feat] #161 - 일기 작성하기 API 값 초기화 및 param 수정
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/PostDiary/PostDiaryRequest.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryForeign/DiaryForeignViewController.swift
Labels: 짠 ✨, Feat

#171 [Fix] #168- 전체 design issue 해결
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/logoSmall.imageset/Contents.json
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/logoSmall.imageset/logoSmall.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/logoSmall.imageset/logoSmall@2x.png
  Smeme-iOS/Smeme-iOS/Resources/Asset/Assets.xcassets/logoSmall.imageset/logoSmall@3x.png
  Smeme-iOS/Smeme-iOS/Resources/Constant/Image.swift
  Smeme-iOS/Smeme-iOS/Resources/DesignSystem/RandomSubjectView.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/DetailOpenDiary/DetailOpenDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/DetailMyDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/Subviews/MyDiaryNavigationBar.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/OpenDiary/OpenDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/ScrapStash/ScrapStashViewController.swift
Labels: 쭈 🏋️‍♀️, Fix

#175 [Feat] #174 - 서버에서 오는 데이터 한국 시간으로 변경
  Smeme-iOS/Smeme-iOS/Resources/Extension/String+.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/DetailMyDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryCollectionViewCell.swift
Labels: 쭈 🏋️‍♀️, Feat

#176 [Feat] #172 - floating 버튼 클릭해서 나오는 뷰에서 배경 클릭 시 이전화면으로 돌아가기
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryFloatingButtonViewController.swift
Labels: 쭈 🏋️‍♀️, Feat

#179 [Feat] #170 - 한국어로 일기 작성하기 API 연결
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Sources/Network/API/Papago/PapagoAPI.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Base/URLConstant.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/Papago/PapagoResponse.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Service/PapagoService/PapagoService.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryForeign/DiaryForeignViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryKorean/StepOneKoreanDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryKorean/StepTwoKoreanDiaryViewController.swift
Labels: 짠 ✨, Feat

#180 [Fix] #177 - 상수파일 enum으로 변경
  Smeme-iOS/Smeme-iOS/Resources/Constant/Constant.swift
  Smeme-iOS/Smeme-iOS/Resources/Constant/Image.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Base/NetworkConstant.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Base/URLConstant.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/PostDiary/PostDiaryRequest.swift
Labels: 쭈 🏋️‍♀️, Fix

#181 [Docs] #173 - readme for final assignment
  README.md
Labels: 쫑 🎀, Docs

#186 [Fix] #185 - OpenDiaryView 기기대응 cell 높이 수정
  Smeme-iOS/Smeme-iOS/Resources/Extension/UILabel+.swift
  Smeme-iOS/Smeme-iOS/Resources/Extension/UIViewController+.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/DetailOpenDiary/DetailOpenDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/DetailMyDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryCollectionViewCell.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/Subviews/LikeBottomView.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/OpenDiary/OpenDiaryViewController.swift
Labels: 쭈 🏋️‍♀️, Fix

#187 [Feat] #170 - 텍스트뷰 입력시 정규식 제한 적용
  Smeme-iOS/Smeme-iOS/Resources/Extension/String+.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryForeign/DiaryForeignViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryKorean/StepOneKoreanDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryKorean/StepTwoKoreanDiaryViewController.swift
Labels: 짠 ✨, Chore

#190 [Chore] #189 - QA 반영
  Smeme-iOS/Smeme-iOS.xcodeproj/project.pbxproj
  Smeme-iOS/Smeme-iOS/Resources/Extension/String+.swift
  Smeme-iOS/Smeme-iOS/Resources/Protocol/ViewModel.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/API/MyDiary/MyDiaryAPI.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/API/MySmeme/MySmemeAPI.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/API/SignUp/SignUpAPI.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/MyDiary/MyDiaryDetailResponse.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/MyDiary/MyDiaryListResponse.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/MySmeme/MySmemeResponse.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/DataModel/SracpOpen/ScrapedStashResponse.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Service/MyDiary/MyDiaryService.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Service/MySmeme/MySmemeService.swift
  Smeme-iOS/Smeme-iOS/Sources/Network/Service/SignUp/SignUpService.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/DetailOpenDiary/DetailOpenDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryForeign/DiaryForeignViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryKorean/StepOneKoreanDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryKorean/StepTwoKoreanDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/MyDiary/MyDiaryFloatingButtonViewController.swift
Labels: 쫑 🎀, Chore

#192 [Chore] #191 - 토스트메세지 레이아웃 수정
  Smeme-iOS/Smeme-iOS/Resources/Extension/UIViewController+.swift
Labels: 쫑 🎀, Chore

#194 [Chore] #193 - 한글 정규식 카운트 이슈 해결
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryForeign/DiaryForeignViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryKorean/StepOneKoreanDiaryViewController.swift
  Smeme-iOS/Smeme-iOS/Sources/Screen/DiaryKorean/StepTwoKoreanDiaryViewController.swift
Labels: 쭌 👳‍♂️, Chore
